gwpopulation/hyperpe.py, setup.py, test/likelihood_test.py
Remove the `sampling_prior` argument from the likelihoods.
=> begin deprecating sampling_prior argument

gwpopulation/utils.py, test/utils_test.py
The powerlaw distribution failed for alpha=-1 due to not accounting for the special case.
=> Fix powerlaw log uniform

gwpopulation/utils.py
Received this error with vanilla installation. Fixed when forcing low to xp.asarray(low), 
File "/home/cbk632/.conda/envs/second_gen/lib/python3.6/site-packages/gwpopula
tion/utils.py", line 28, in powerlaw
if xp.any(low < 0):
File "/home/cbk632/.conda/envs/second_gen/lib/python3.6/site-packages/cupy/log
ic/truth.py", line 58, in any
assert isinstance(a, cupy.ndarray)
AssertionError
=> AssertionError on some installations

gwpopulation/hyperpe.py, test/likelihood_test.py
Removes `samples_factor` and includes the calculation in the `_compute_per_event_ln_bayes_factors`.
This makes sure the `generate_extra_statistics` function includes the 1/samples term.
=> Edit _compute_per_event_ln_bayes_factors to include number of samples

gwpopulation/hyperpe.py
As of right now, the `HyperparameterLikelihood` class in `gwpopulation` wraps any input models (`hyper_prior`) in `bilby`'s `Model` class if those input models are not already Model() classes. However, `gwdistributions` population models are either `SamplingDistribution` or `EventGenerator` classes, which have the same methods as `Model` plus more functionality, so they should not be wrapped in the `Model` class. This PR presents a simple solution, suggested by @reedessick, where functions passed as `hyper_prior`s to 'HyperparameterLikelihood` are still wrapped in the `Model` class, but other types (i.e. classes) are not wrapped.
=> Add hyper_prior compatibility with `gwdistributions` classes

gwpopulation/models/redshift.py, gwpopulation/vt.py, test/likelihood_test.py
The `total_spacetime_volume` and `normalisation` methods were doing the same thing.
=> Remove redshift duplicate

gwpopulation/models/mass.py
This PR removes a bunch of duplicate boiler plate code in the smoothed mass distributions. It also removes the deprecated `SmoothedMassDistribution` and reveals the `BaseSmoothedMassDistribution` class.
=> Rationalize smoothed mass distribution code

gwpopulation/models/redshift.py, test/redshift_test.py
Currently `z_max` is not applied properly in the `Redshift` models, see the plot below. This PR will fix that.
=> fix application of bounds in redshift model

.travis.yml, docs/conf.py, gwpopulation/conversions.py, gwpopulation/cupy_utils.py, gwpopulation/hyperpe.py, gwpopulation/models/mass.py, gwpopulation/models/redshift.py, gwpopulation/utils.py, gwpopulation/vt.py, setup.cfg, setup.py, test/likelihood_test.py, test/redshift_test.py
- Require `Python>=3.8`
- Allow `cupy>=10.1`
- Typo fixes
=> fixes for updated cupy/python versions

.github/workflows/pages.yml, .github/workflows/python-package.yml, .pre-commit-config.yaml, docs/conf.py
Currently, the `jupyter` examples aren't rendering properly in the online documentation, this will resolve that.
There's also a fix to allow `codespell` to run on notebooks that contain output.
=> Fix jupyter docs

MANIFEST.in, gwpopulation/hyperpe.py, gwpopulation/models/redshift.py, setup.py
- Make requirements consistent in `setup.py` and `requirements.txt`
- Remove top-level imports of `pandas`, `astropy`, `tqdm`, `scipy.stats`
- Remove the creation of the `PowerLawRedshift` instance on import
=> Reduce top level imports

gwpopulation/hyperpe.py, test/likelihood_test.py
This PR adds some metadata to the likelihood object, this will automatically be stored in a `Bilby` result and will help make it easier to do various bits of post-processing.
=> add meta data to likelihood

gwpopulation/models/mass.py, gwpopulation/models/redshift.py, requirements.txt
As of Bilby==1.2.0 the `bilby.hyper.model.Model` can use a `variable_names` attribute/property rather than introspection to get the parameters for a specific model.
This allows some of the boilerplate code in the smoothed mass distributions to be removed.
=> MAINT: use Bilby variable_names

gwpopulation/vt.py, test/example_test.py, test/vt_test.py
This PR changes the default call of the ResamplingVT to use the estimator of the Monte Carlo rather than the marginalized pdet from [Farr 2019](https://arxiv.org/abs/1904.10879). Justification: see top of pg 14 on [Essick & Farr](https://arxiv.org/pdf/2204.00461.pdf) for example.
=> added change to vt.py to use mu rather than marginalized pdet

gwpopulation/vt.py
I realized that when we changed the ResamplingVT object to return the mu and var by default (rather than the vt_factor), we got rid of the ability to enforce the n_eff > 4*n_obs condition. This PR adds a flag to include this check before returning the mu, var values in the __call__.
=> Add convergence check for default __call__ behavior in vt

gwpopulation/__init__.py, gwpopulation/backend.py, gwpopulation/hyperpe.py, gwpopulation/models/mass.py, test/backend_test.py
This PR allows downstream packages to define a `gwpopulation.xp` or `gwpopulation.scs` plugin that will automatically propagate changes to the gwpopulation backend, e.g., for gwpopulation_pipe.
I also fixed a bug that appeared with numpy/cupy division.
=> Plugin backend usage

gwpopulation/models/mass.py
There is slight difference between numpy.where and cupy.where. For cupy.where, it seems a 'bool' object is not allowed as condition.
Update xp.where(delta_m > 0, xxx, yyy) in mass model by xp.where(xp.array(delta_m) > 0, xxx, yyy).
=> fix cupy.where error for mass model

gwpopulation/models/interped.py, gwpopulation/models/mass.py, gwpopulation/models/spin.py, test/interped_test.py
This PR adds an option to provide an explicit regularization for the exponentiated spline models.
This defines one new parameter per mode `rms{name}`.
Each of the `f{name}` parameters are scaled such that the root-mean-square value of `f{name}` is `rms{name}`.
=> DEV: add regularization option for spline interpolated models

gwpopulation/backend.py, setup.cfg, test/backend_test.py
I wanted to be able to use `scipy.linalg.toeplitz` and that wasn't possible to vary the backend for.
I added a new more flexible interface to provide specific scipy functionality manually using a `gwpopulation.others` option.
I also added an example of how to specify this to the docs and moved the gwpopulation native ones to `setup.cfg` to avoid having to special case the internal changes.
=> FEAT: allow arbitrary scipy modifications

gwpopulation/models/mass.py
=> TYPO: fix typo in __all__ mass models

gwpopulation/utils.py, test/utils_test.py
I had reports of bad normalization for truncnorm when the mean was many sigma away from the support. The new method more closely aligns with scipy.
=> ENH: make truncnorm more robust

gwpopulation/utils.py
`cupy` enforces that the default argument to `select` is a scalar. This brings us in line with that.
=> BUG: make select default scalar

gwpopulation/models/spin.py, priors/bbh_population.prior, priors/spin.prior, test/example_test.py
This PR allows the user to specify the mean of the Gaussian component of the spin tilt model in `iid_spin_orientation_gaussian_isotropic` and `independent_spin_orientation_gaussian_isotropic`. Defaults to the old model with `mu_spin = 1`. Docstrings are updated to reflect the change.
=> Add flexibility to gaussian spin tilt
